package com.cmos.app.dao.dao;

import com.cmos.app.bean.RolesPermissions;
import com.cmos.app.bean.RolesPermissionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    long countByExample(RolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int deleteByExample(RolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int insert(RolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int insertSelective(RolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    List<RolesPermissions> selectByExample(RolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    RolesPermissions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") RolesPermissions record, @Param("example") RolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int updateByExample(@Param("record") RolesPermissions record, @Param("example") RolesPermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int updateByPrimaryKeySelective(RolesPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_permissions
     *
     * @mbg.generated Fri Mar 22 14:36:51 CST 2019
     */
    int updateByPrimaryKey(RolesPermissions record);
}